### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by raygesualdo** [elynde/glow-js#1]
Thanks for doing this! I tried to find documentation on Glow Baby's API and there was nothing. Nice job reverse engineering this. I was able to replicate your code in Postman and pull down data from my account.

Question: how did you reverse engineer the API calls? I'd like to try to log entries via the API, but don't have the contracts for those API calls.

**Comment by elynde** [comment]
Ah ya this part was tricky.

I downloaded the APK from a sketchy APK mirror site and installed it in an
emulator on my computer. Then I tried using Charles Proxy to intercept the
traffic.

Unfortunately this didn't work because the app used SSL with cert pinning
so Charles failed to fake like it's the server. Luckily someone showed me
that it's actually not that difficult to just decompile an app, remove the
cert pinning code and then recompile it. I did that based off these
instructions
https://medium.com/@targetpractice/disabling-okhttps-ssl-pinning-on-android-bd116aa74e05
.

I'd send you the APK but it was a long time ago on an old computer I don't
have anymore. All this sounds difficult but if you follow the instructions
carefully you should be able to pull it off!

**Comment by raygesualdo** [comment]
Dang! I thought it might get complicated. Thanks for the info. I'll give that a shot.

**Comment by trey-sedate** [comment]
@raygesualdo Were you able to reverse engineer any of the logging API calls? I'm finding myself in a similar position today.

**Comment by raygesualdo** [comment]
Sadly no. I tried to reverse engineer the APK to introspect the requests but was unsuccessful. We also stopped using the app a few weeks later, so the incentive wasn't there 😂
